불필요한 파일 제거, 주소 수정
see-the-glory/on-you-backend pull request #21
Opened 2022-03-20 16:36 UTC by ajaekwang

1. 테스트용 html 파일 제거
2. rest api 주소 수정

TODO
entity join 하기

2022-03-20 16:44 UTC, ajaekwang commented
도커 빌드하는데 문제가 있는거 같은데 한번 봐주셈

2022-03-22 04:39 UTC, jjunyong commented
음 아마 앞에 제거 PR 머지하면 문제 없을 것 같아요

2022-03-22 04:49 UTC, jjunyong requested changes
리뷰 완료

2022-03-22 04:49 UTC, jjunyong commented on src/main/java/stg/onyou/controller/FeedController.java
> +    public String createFeed(@RequestBody Feed feedForm) {
Feed 타입으로 받으면 안되고 DTO를 만들어 주세요

2022-03-22 04:49 UTC, jjunyong commented on src/main/java/stg/onyou/model/entity/Feed.java
> +    private Integer reportCount = 0;
@Column(columnDefinition = "integer default 0")
이렇게 JPA의 어노테이션 활용해서 디폴트 값 설정해주세요

2022-03-22 04:49 UTC, jjunyong commented on src/main/java/stg/onyou/model/entity/Feed.java
> +    private Integer reportCount = 0;
그리고 userId, groupId(clubId겟죠?) 이런 식으로 id 값을 Entity에서 가지고 있으면 안됨. 
그러면 Feed.getUser() 이런 식으로 객체 지향적인 접근이 안되거든요. 
User, Club 참조 값을 멤버로 가지고 있어야 돼요. 그걸 id값이랑 매핑해주는건 JPA가 해줌

2022-03-22 04:49 UTC, jjunyong commented on src/main/java/stg/onyou/controller/FeedController.java
> +    @GetMapping("/recent")
api path가 왜 /api/feeds/recent 인가요? 
/api/feeds 에 query param이 추가된 형태가 맞는 것 같아요

2022-04-02 02:17 UTC, ajaekwang commented on src/main/java/stg/onyou/controller/FeedController.java
> +    public String createFeed(@RequestBody Feed feedForm) {
front에서 feed 정보를 @RequestBody로 담을 생각이었는데 Feed로 받으면 안되고 DTO로 만들어야 한다는것이 왜 그런지 잘 모르겠어. 이유 설명해주면 감사여

2022-04-02 02:37 UTC, jjunyong commented on src/main/java/stg/onyou/controller/FeedController.java
> +    public String createFeed(@RequestBody Feed feedForm) {
Request body랑은 상관없어요
MVC에서 view와 model이 분리되어 있고 역할도 서로 다르 잖아요.
Feed 엔티티(model)로 바로 프론트항 데이터를 주고 받게 되면  view와 model의 역할 분리가 되지도 않고 ApI 스펙이 model이 달라짐에 따라 계속 수정도 필요하겠죠
순환 참조의 문제도 생길거구요
구글에 dto와 entity를 분리해서 써야 하는 이유에 대해 찾아보면 잘 나와 있어요.
Jpa 순환참조 관련해서도 찾아보고~!

2022-04-17 15:47 UTC, merged