20220414 security
see-the-glory/on-you-backend pull request #28
Opened 2022-04-14 15:14 UTC by jjunyong

카카오 로그인을 위한 Spring Security 설정 ( 테스트 )

2022-04-15 15:57 UTC, neocurian requested changes

2022-04-15 15:57 UTC, neocurian commented on src/main/java/stg/onyou/config/jwt/AccessTokenAuthenticationProvider.java
> +                        .role(Role.USER).build()));//없다면 멤버를 새로 만드는데, USER가 아니라 GUEST로 설정했다. 이는 아래해서 설명한다
주석이 잘 못 된거 같네. 코드를 보면 GUEST는 없는데

2022-04-15 15:57 UTC, neocurian commented on src/main/java/stg/onyou/config/jwt/JwtAuthenticationFilter.java
> +        System.out.println("JwtAuthenticationFilter : 진입");
커밋 할때는 프린트 지우던가 아니면 로그 처리하는게 좋을 것 같아요

2022-04-15 15:57 UTC, neocurian commented on src/main/java/stg/onyou/config/jwt/JwtAuthorizationFilter.java
> +            User user = userRepository.findByName(username);
findByName 으로 하면 동명이인이 있는 경우에는 문제가 되지 않을까?

2022-04-15 15:57 UTC, neocurian commented on src/main/java/stg/onyou/config/auth/PrincipalDetails.java
> +        return null;
왜 권한이 항상 null 일까?

2022-04-16 11:13 UTC, jjunyong commented on src/main/java/stg/onyou/config/jwt/AccessTokenAuthenticationProvider.java
> +                        .role(Role.USER).build()));//없다면 멤버를 새로 만드는데, USER가 아니라 GUEST로 설정했다. 이는 아래해서 설명한다
맞아요 주석 다음에 수정할게요~!

2022-04-16 11:14 UTC, jjunyong commented on src/main/java/stg/onyou/config/jwt/JwtAuthorizationFilter.java
> +            User user = userRepository.findByName(username);
넵 아직 개발 완료된 건 아니라서 이거도 수정할 예정이었어요

2022-04-16 11:14 UTC, jjunyong commented on src/main/java/stg/onyou/config/auth/PrincipalDetails.java
> +        return null;
이것도 임시로 이렇게 해 둔거에요 ..ㅎㅎ

2022-04-16 11:15 UTC, jjunyong commented on src/main/java/stg/onyou/config/jwt/JwtAuthenticationFilter.java
> +        System.out.println("JwtAuthenticationFilter : 진입");
넵넵

2022-04-17 14:47 UTC, neocurian approved these changes

2022-04-18 14:43 UTC, ajaekwang commented
security 관해서 1도 몰라서 저는 패스요. 
코드는 확인

2022-04-18 14:43 UTC, ajaekwang approved these changes

2022-04-18 14:43 UTC, ajaekwang approved these changes

2022-04-19 01:38 UTC, merged