spring feed 관련 코드 개발
see-the-glory/on-you-backend pull request #7
Opened 2022-03-02 03:04 UTC by ajaekwang

feed 관련 controller, service, repository, model 코드

2022-03-02 06:34 UTC, jjunyong requested changes
확인 후 의견 주세요 :)

2022-03-02 06:34 UTC, jjunyong commented on src/main/java/stg/onyou/model/entity/Feed.java
> +    private String title;
content 가 빠진 것 같아요

2022-03-02 06:34 UTC, jjunyong commented on src/main/java/stg/onyou/repository/FeedRepository.java
> +public interface FeedRepository {
FeedRepository를 @Repository로 두고, extends JpaRepository<Feed,Long> 을 해야 될 것 같아요.
이렇게 하면 형이 구현한 것처럼 직접 findFeedList와 같이 메소드를 선언할 필요도 없고(JpaRepository에 다 구현되어 있음)
FeedRepositoryImpl 클래스도 필요없게 됩니다.

2022-03-02 06:34 UTC, jjunyong commented on src/main/java/stg/onyou/repository/FeedRepositoryImpl.java
> +package stg.onyou.repository;
위에 제가 댓글 단 것처럼 해당 클래스는 필요가 없을 것 같아요

2022-03-02 06:34 UTC, jjunyong commented on src/main/java/stg/onyou/service/FeedService.java
> +    private final FeedRepositoryImpl feedRepository;
여기도 Impl 클래스를 사용하지 않는 방향으로 구현하면 좋을 것 같습니다.

2022-03-05 09:50 UTC, ajaekwang commented on src/main/java/stg/onyou/repository/FeedRepository.java
> +public interface FeedRepository {
JPA 공부해서 적용해볼게

2022-03-08 09:07 UTC, merged